name: CI

on:
  workflow_dispatch:

jobs:
  detect-secrest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: detect secrets
      run: | 
      pip install detect-secrets
